# Generated by Django 3.2 on 2023-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('venereal', models.CharField(max_length=20, null=True)),
                ('birth_year', models.IntegerField()),
                ('boobs', models.IntegerField()),
            ],
        ),
    ]
