# Generated by Django 3.2 on 2023-05-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='whore',
            table='whore',
        ),
    ]
