# Generated by Django 4.2 on 2023-05-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whore', '0003_whore_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='whore',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whore', to='whore.owner'),
            preserve_default=False,
        ),
    ]
