# Generated by Django 4.2 on 2023-05-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whore', '0004_owner_whore_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementWhore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whore.achievement')),
                ('whore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whore.whore')),
            ],
        ),
        migrations.AddField(
            model_name='whore',
            name='achievements',
            field=models.ManyToManyField(through='whore.AchievementWhore', to='whore.achievement'),
        ),
    ]
