# Generated by Django 4.2 on 2023-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whore', '0005_achievement_achievementwhore_whore_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='whore',
            name='panty_color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
