# Generated by Django 4.2 on 2023-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whore', '0007_alter_whore_owner_alter_whore_table_delete_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='whore',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_owner'),
        ),
    ]
